eureka:
  client:
    serviceUrl:
      defaultZone: http://book_eureka:8761/eureka/
server:
  port: 9088
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: roles-service
          uri: http://localhost:9089
          predicates:
            - Path=/roles/**
          filters:
            - AuthFilter
        - id: user-service
          uri: http://localhost:9091
          predicates:
            - Path=/user/**
          filters:
            - AuthFilter
        - id: fitness-service
          uri: http://localhost:9092
          predicates:
            - Path=/auth/**
          filters:
            - AuthFilter
        - id: diet-service
          uri: http://localhost:9093
          predicates:
            - Path=/auth/**
          filters:
            - AuthFilter
        - id: wellbeing-service
          uri: http://localhost:9094
          predicates:
            - Path=/wellbeing/**
          filters:
            - AuthFilter
        - id: authentication-server
          uri: http://localhost:9090
          predicates:
            - Path=/auth/**