eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9088
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:5173"
            allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
            allowed-headers: "Authorization, Content-Type, X-Requested-With, Accept"
            allow-credentials: true
            max-age: 3600
      discovery:
        locator:
          enabled: true
      routes:
        - id: roles-service
          uri: http://localhost:9089
          predicates:
            - Path=/roles/**
        - id: user-service
          uri: http://localhost:9091
          predicates:
            - Path=/user/**
          filters:
            - AuthFilter
        - id: fitness-service
          uri: http://localhost:9092
          predicates:
            - Path=/health/fitness/**
          filters:
            - AuthFilter
        - id: diet-service
          uri: http://localhost:9093
          predicates:
            - Path=/diet/**
          filters:
            - AuthFilter
        - id: wellbeing-service
          uri: http://localhost:9094
          predicates:
            - Path=/wellbeing/**
          filters:
            - AuthFilter
        - id: report-service
          uri: http://localhost:9095
          predicates:
            - Path=/report/**
          filters:
            - AuthFilter
        - id: authentication-server
          uri: http://localhost:9090
          predicates:
            - Path=/auth/**